import type { Metadata } from 'next';
import '../styles/globals.css';
import Header from '@/components/modules/Header/Header';
import Footer from '@/components/modules/Footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='fa'>
      <body
        className={`bg-background-light font-pinar font-normal text-text-light antialiased dark:bg-background-dark dark:text-text-dark`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
